// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipleComplaintMgmtSys.API.ComplaintContext;

#nullable disable

namespace MunicipleComplaintMgmtSys.API.Migrations
{
    [DbContext(typeof(ComplaintDBContext))]
    [Migration("20250926065746_UpdateOfficial")]
    partial class UpdateOfficial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultSlaHours")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AssignedWorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReopened")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintId");

                    b.HasIndex("AssignedWorkerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TicketNo")
                        .IsUnique();

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.ComplaintAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("AttachmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WorkUpdateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttachmentId");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("WorkUpdateId");

                    b.ToTable("ComplaintAttachments");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSatisfied")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ComplaintId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Official", b =>
                {
                    b.Property<Guid>("OfficialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OfficialId");

                    b.HasIndex("UserId");

                    b.ToTable("Officials");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.OfficialDepartment", b =>
                {
                    b.Property<Guid>("OfficialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("OfficialId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("OfficialDepartments");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SlaHours")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.WorkUpdate", b =>
                {
                    b.Property<Guid>("WorkUpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalResourcesNeeded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAdditionalResources")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkUpdateId");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("WorkUpdates");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkerId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.AuditLog", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Category", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Department", "Department")
                        .WithMany("Categories")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Complaint", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Worker", "AssignedWorker")
                        .WithMany("AssignedComplaints")
                        .HasForeignKey("AssignedWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Category", "Category")
                        .WithMany("Complaints")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "Citizen")
                        .WithMany("Complaints")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.SubCategory", "SubCategory")
                        .WithMany("Complaints")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedWorker");

                    b.Navigation("Category");

                    b.Navigation("Citizen");

                    b.Navigation("Department");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.ComplaintAttachment", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Complaint", "Complaint")
                        .WithMany("Attachments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.WorkUpdate", null)
                        .WithMany("Attachments")
                        .HasForeignKey("WorkUpdateId");

                    b.Navigation("Complaint");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Feedback", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Complaint", "Complaint")
                        .WithOne("Feedback")
                        .HasForeignKey("MunicipleComplaintMgmtSys.API.Models.Feedback", "ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Official", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.OfficialDepartment", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Department", "Department")
                        .WithMany("OfficialDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Official", "Official")
                        .WithMany("OfficialDepartments")
                        .HasForeignKey("OfficialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Official");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.SubCategory", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.WorkUpdate", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Complaint", "Complaint")
                        .WithMany("WorkUpdates")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Worker", b =>
                {
                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.Department", "Department")
                        .WithMany("Workers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MunicipleComplaintMgmtSys.API.Models.User", "User")
                        .WithOne("WorkerProfile")
                        .HasForeignKey("MunicipleComplaintMgmtSys.API.Models.Worker", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Category", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Complaint", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Feedback");

                    b.Navigation("WorkUpdates");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Department", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Complaints");

                    b.Navigation("OfficialDepartments");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Official", b =>
                {
                    b.Navigation("OfficialDepartments");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.SubCategory", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.User", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("WorkerProfile");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.WorkUpdate", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MunicipleComplaintMgmtSys.API.Models.Worker", b =>
                {
                    b.Navigation("AssignedComplaints");
                });
#pragma warning restore 612, 618
        }
    }
}
